### ISSUE TITLE
Issue 1 : Remove Emails from Robo Friends | Front End

### ISSUE THREAD

**Issue by Meluvy** [zanemooney/robofriends_cis486#1]
## Developer Story Card
**As a..** developer
**I want..** to delete emails in our robot friends application.
**So That..** we get rid of unnecessary stuff.

## Requested Tasks
- [x] Go to the card.js file and delete the email p tag. 
- [x] Remove the emails from the back end.

**Comment by KatrinaYates** [comment]
I have completed this issue. However, I pushed to the main branch instead of creating a new branch and making a pull request.

Code for after email removal in Card.js
```
<div>
    <h2>{name}</h2>
</div>
```
