### ISSUE TITLE
Issue 11: Adding Library for Icons

### ISSUE THREAD

**Issue by Meluvy** [zanemooney/robofriends_cis486#11]
## Developer Story Card
**As a..** developer
**I want..** to upload a library onto the main branch.
**So That..** we can use icons for upvoting/downvoting, etc.

**Comment by Meluvy** [comment]
https://react-icons.github.io/react-icons/icons?name=bs 

>React Library to replace our assets folder

**Comment by zanemooney** [comment]
https://github.com/zanemooney/robofriends_cis486/pull/12
