### ISSUE TITLE
Issue 3 : Change Format to Vertical Scrolling Robot Pictures

### ISSUE THREAD

**Issue by zanemooney** [zanemooney/robofriends_cis486#3]
## Developer Story Card
**As a..** developer
**I want..** make a stacked column of robot pictures and add new _sticky profiles_ on both sides of UI.
**So That..** we can streamline the UI of our application and add more functionality. 

## Requested Tasks
- [ ] Take the cards and put them in a div
- [ ] Create one long column that is vertical
- [ ] Add information on sticky profiles of each developer.

**Comment by zanemooney** [comment]
https://github.com/zanemooney/robofriends_cis486/commit/7df42a61dd58082c98db97251643fdf8986bcc70

**Comment by KatrinaYates** [comment]
I have completed this issue. However, I pushed to the main branch instead of creating a new branch and making a pull request.

Reformatted the robots in Scroll.js
```
<div style={{overflow: "scroll", border: "5px solid black", height: "800px", width: "400px"}}>
    {props.children}
</div>
```

Adding the profiles on each side of robots in App.js:
```
<section className="flex justify-around mr2">
    <GirlDevs />
    <Scroll>
        <CardList robots={filteredRobots}/>
    </Scroll>
    <BoyDevs />
</section>
```
