### ISSUE TITLE
Issue 7: Alter the DOM ID's

### ISSUE THREAD

**Issue by mjohnson7cd** [zanemooney/robofriends_cis486#7]
As a developer,
I want to remove confusing identifiers from our code,
So that it is easier to implement on the front end. 

Alter the DOM ID's for the event listeners on up and down vote buttons. Link the new DOM ID's with the database ID's inside main.js

**Comment by zanemooney** [comment]
https://github.com/zanemooney/robofriends_cis486/commit/7047817e52a8a5c04e7ea1e04fc5471fa77ca7c8

Link to commit link. Done by Mark.
